import Content from "@/components/Content";
import Sidebar from "@/components/Sidebar";
import { TagCount } from "@/pages/api/tags";
import { styled } from "@/stitches.config";
import Head from "next/head";
import { useEffect, useState } from "react";

const Main = styled("main", {
  display: "flex",
  flexDirection: "row",
  height: "100%",
});

export default function Home() {
  const [topTags, setTopTags] = useState<TagCount[]>([]);
  const [selectedTag, setSelectedTag] = useState("");
  const [savedTags, setSavedTags] = useState<Set<string>>(new Set(["Arsenal"]));

  useEffect(() => {
    async function fetchTags() {
      const response = await fetch("/api/tags", {
        method: "GET",
      });

      return response.json();
    }

    fetchTags().then((body) => {
      setTopTags(body.tags);
    });
  }, []);

  return (
    <>
      <Head>
        <title>HiveCaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-row">
          <Sidebar
            topTags={topTags}
            savedTags={savedTags}
            setSelectedTag={setSelectedTag}
            setSavedTags={setSavedTags}
          />
          <Content selectedTag={selectedTag} topTags={topTags} />
        </div>
      </main>
    </>
  );
}
