import { styled } from "@/stitches.config";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import { useEffect, useState } from "react";

const Text = styled("p", {
  fontFamily: "$system",
  color: "$hiContrast",

  variants: {
    size: {
      1: {
        fontSize: "$1",
      },
      2: {
        fontSize: "$2",
      },
      3: {
        fontSize: "$3",
      },
    },
  },
});

export default function Home() {
  const [categories, setCategories] = useState([]);

  useEffect(() => {
    async function fetchCategories() {
      const response = await fetch("/api/categories", {
        method: "GET",
      });

      return response.json();
    }

    fetchCategories().then((body) => {
      setCategories(body.categories);
    });
  }, []);

  console.log(categories);

  return (
    <>
      <Head>
        <title>Hivetag</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text as="h1" size="2">
          Hello World
        </Text>

        {categories.map((category) => {
          return <div key={category}>{category}</div>;
        })}
      </main>
    </>
  );
}
